package com.hospital.mybatis.dao;

import com.hospital.mybatis.model.Hospital;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface HospitalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.HOSPITAL
     *
     * @mbg.generated Wed Apr 27 14:58:55 EEST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.HOSPITAL
     *
     * @mbg.generated Wed Apr 27 14:58:55 EEST 2022
     */
    int insert(Hospital record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.HOSPITAL
     *
     * @mbg.generated Wed Apr 27 14:58:55 EEST 2022
     */
    Hospital selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.HOSPITAL
     *
     * @mbg.generated Wed Apr 27 14:58:55 EEST 2022
     */
    List<Hospital> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.HOSPITAL
     *
     * @mbg.generated Wed Apr 27 14:58:55 EEST 2022
     */
    int updateByPrimaryKey(Hospital record);
}