package com.hospital.mybatis.dao;

import com.hospital.mybatis.model.Illness;
import java.util.List;

public interface IllnessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ILLNESS
     *
     * @mbg.generated Wed Apr 27 14:58:55 EEST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ILLNESS
     *
     * @mbg.generated Wed Apr 27 14:58:55 EEST 2022
     */
    int insert(Illness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ILLNESS
     *
     * @mbg.generated Wed Apr 27 14:58:55 EEST 2022
     */
    Illness selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ILLNESS
     *
     * @mbg.generated Wed Apr 27 14:58:55 EEST 2022
     */
    List<Illness> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ILLNESS
     *
     * @mbg.generated Wed Apr 27 14:58:55 EEST 2022
     */
    int updateByPrimaryKey(Illness record);
}