package com.hospital.mybatis.dao;

import com.hospital.mybatis.model.Patient;
import java.util.List;

public interface PatientMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PATIENT
     *
     * @mbg.generated Wed Apr 27 14:58:55 EEST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PATIENT
     *
     * @mbg.generated Wed Apr 27 14:58:55 EEST 2022
     */
    int insert(Patient record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PATIENT
     *
     * @mbg.generated Wed Apr 27 14:58:55 EEST 2022
     */
    Patient selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PATIENT
     *
     * @mbg.generated Wed Apr 27 14:58:55 EEST 2022
     */
    List<Patient> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PATIENT
     *
     * @mbg.generated Wed Apr 27 14:58:55 EEST 2022
     */
    int updateByPrimaryKey(Patient record);
}