package com.hospital.mybatis.model;

public class Illness {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ILLNESS.ID
     *
     * @mbg.generated Wed Apr 27 14:58:55 EEST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ILLNESS.TYPE
     *
     * @mbg.generated Wed Apr 27 14:58:55 EEST 2022
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ILLNESS.ID
     *
     * @return the value of PUBLIC.ILLNESS.ID
     *
     * @mbg.generated Wed Apr 27 14:58:55 EEST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ILLNESS.ID
     *
     * @param id the value for PUBLIC.ILLNESS.ID
     *
     * @mbg.generated Wed Apr 27 14:58:55 EEST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ILLNESS.TYPE
     *
     * @return the value of PUBLIC.ILLNESS.TYPE
     *
     * @mbg.generated Wed Apr 27 14:58:55 EEST 2022
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ILLNESS.TYPE
     *
     * @param type the value for PUBLIC.ILLNESS.TYPE
     *
     * @mbg.generated Wed Apr 27 14:58:55 EEST 2022
     */
    public void setType(String type) {
        this.type = type;
    }
}