package com.hospital.mybatis.model;

public class Patient {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PATIENT.ID
     *
     * @mbg.generated Wed Apr 27 14:58:55 EEST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PATIENT.NAME
     *
     * @mbg.generated Wed Apr 27 14:58:55 EEST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PATIENT.SURNAME
     *
     * @mbg.generated Wed Apr 27 14:58:55 EEST 2022
     */
    private String surname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PATIENT.HOSPITAL_ID
     *
     * @mbg.generated Wed Apr 27 14:58:55 EEST 2022
     */
    private Integer hospitalId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PATIENT.ID
     *
     * @return the value of PUBLIC.PATIENT.ID
     *
     * @mbg.generated Wed Apr 27 14:58:55 EEST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PATIENT.ID
     *
     * @param id the value for PUBLIC.PATIENT.ID
     *
     * @mbg.generated Wed Apr 27 14:58:55 EEST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PATIENT.NAME
     *
     * @return the value of PUBLIC.PATIENT.NAME
     *
     * @mbg.generated Wed Apr 27 14:58:55 EEST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PATIENT.NAME
     *
     * @param name the value for PUBLIC.PATIENT.NAME
     *
     * @mbg.generated Wed Apr 27 14:58:55 EEST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PATIENT.SURNAME
     *
     * @return the value of PUBLIC.PATIENT.SURNAME
     *
     * @mbg.generated Wed Apr 27 14:58:55 EEST 2022
     */
    public String getSurname() {
        return surname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PATIENT.SURNAME
     *
     * @param surname the value for PUBLIC.PATIENT.SURNAME
     *
     * @mbg.generated Wed Apr 27 14:58:55 EEST 2022
     */
    public void setSurname(String surname) {
        this.surname = surname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PATIENT.HOSPITAL_ID
     *
     * @return the value of PUBLIC.PATIENT.HOSPITAL_ID
     *
     * @mbg.generated Wed Apr 27 14:58:55 EEST 2022
     */
    public Integer getHospitalId() {
        return hospitalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PATIENT.HOSPITAL_ID
     *
     * @param hospitalId the value for PUBLIC.PATIENT.HOSPITAL_ID
     *
     * @mbg.generated Wed Apr 27 14:58:55 EEST 2022
     */
    public void setHospitalId(Integer hospitalId) {
        this.hospitalId = hospitalId;
    }
}